[package]
name = "monster-telemetry"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
async-trait.workspace = true
chrono.workspace = true
sysinfo = "0.31"
bytesize = "1"

monster-bus = { path = "../monster-bus" }
