[package]
name = "monster-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
dirs.workspace = true
rusqlite.workspace = true
reqwest = { workspace = true, features = ["json"] }
